async page => {
  const origin='http://localhost:8765',checker=origin+'/qc-vendor/axe-4.10.3.min.js',violations=[],scans=[],passed=[],requests=[],errors=[],workers=[],omissions=[],openerChecks=[],glossaries=[];
  const need=(v,m)=>{if(!v)throw Error(m);};
  page.on('request',r=>requests.push({url:r.url(),method:r.method()}));page.on('pageerror',e=>errors.push(e.message));page.on('worker',w=>workers.push(w.url()));
  await page.addInitScript(()=>{const D=Date;window.Date=class extends D{constructor(...a){super(...(a.length?a:['2026-12-30T12:00:00']));}};});
  const safe=async()=>need(await page.locator('#runtime-warning').isHidden(),'Accessible interaction tripped runtime ownership');
  const boot=async()=>{await page.goto(origin+'/');await page.locator('#runtime-warning').waitFor({state:'attached'});await page.locator('#file-support-contract dd').last().waitFor({state:'attached'});await page.locator('#preflight').waitFor({state:'visible'});await safe();};
  const scan=async name=>{if(!await page.evaluate(()=>Boolean(window.axe)))await page.addScriptTag({url:checker});need(await page.evaluate(()=>window.axe.version)==='4.10.3','Pinned accessibility checker changed');const r=await page.evaluate(async()=>window.axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21a','wcag21aa']}}));need(r.passes.length>0&&r.testEngine.version==='4.10.3','Checker did not run actual rules');scans.push({name,version:r.testEngine.version,rulesPassed:r.passes.length,violations:r.violations.length});if(r.violations.length)violations.push({name,issues:r.violations.map(i=>i.id+': '+i.nodes.length+' nodes')});};
  const primary=()=>page.getByRole('button',{name:'Check records',exact:true}),confirm=()=>page.getByRole('button',{name:'I checked this subscription, line, and customer in the original systems',exact:true});
  const heading=async text=>page.waitForFunction(t=>document.querySelector('#record-info > h3')?.textContent===t,text);
  const noGreen=async()=>need((await page.locator('#record-info h3,#record-result h3').allTextContents()).every(t=>!/^(Answers look in scope|Supplied records look in scope provisionally)$/.test(t)),'An unasked reseller gained positive eligibility, including hidden information');
  const quiet=async()=>{
    need(await page.locator('#preflight').isVisible()&&await page.locator('#evidence-panels').isHidden()&&await page.locator('#file-guide').isHidden(),'Controls are not the sole current flow node');
    need(await page.locator('#preflight details,#preflight h2,#preflight h3,#preflight h4').count()===0&&await page.locator('#preflight p:visible:not([role=status])').filter({hasText:/\S/}).count()===0&&await page.locator('#record-result > :not(button)').count()===0,'Body prose or information mixed into controls');
    need(await page.locator('#record-info button,#record-info input,#record-info select').count()===0&&await primary().isHidden()===((await page.locator('#record-result > button').count())>0),'Information contains workflow inputs or Check duplicates actions');
  };
  const readableOpener=async name=>{
    const o=await page.evaluate(async()=>{const n=document.getElementById('open-evidence');if(document.getElementById('preflight').hidden||!document.getElementById('evidence-panels').hidden)throw Error('Readable opener requires controls with information deferred');(await import('/file-evidence-view.mjs')).assertReadableInspectionOpener(n);return{tag:n.tagName,text:n.textContent,href:n.getAttribute('href'),focusable:n.tabIndex>=0,forcedColors:matchMedia('(forced-colors: active)').matches};});
    need(o.tag==='A'&&o.text==='Evidence'&&o.href==='#evidence-panels'&&o.focusable,'Evidence link lost native keyboard/readability contract');openerChecks.push({name,...o});
  };
  const evidence=async()=>{await page.locator('#open-evidence').focus();await page.keyboard.press('Enter');need(await page.locator('#evidence-panels').isVisible()&&await page.locator('#preflight').isHidden()&&await page.locator('#file-guide').isHidden()&&await page.evaluate(()=>document.activeElement.id)==='close-evidence','Keyboard Evidence navigation/focus failed');await safe();};
  const back=async()=>{await page.locator('#close-evidence').focus();await page.keyboard.press('Enter');await quiet();need(await page.evaluate(()=>document.activeElement.id)==='open-evidence','Keyboard information return lost link focus');};
  const glossaryExpected=[
    {term:'Normalized CSV',definition:'Comma-separated UTF-8 data using the example columns. Native exports, XLSX and agreement files are unsupported.'},
    {term:'Pax8 CSV',definition:'Subscription records. Include source_account_id to confirm a case.'},
    {term:'HaloPSA CSV',definition:'Recurring billing records linked by subscription_id and customer_ref.'},
    {term:'Subscription ID',definition:'The exact Pax8 identifier in the subscription_id column.'},
    {term:'Commitment term',definition:'How long the subscription lasts, separate from how often it is billed.'},
    {term:'Original file',definition:'The unchanged file you supplied, available to inspect or save.'},
    {"term": "File use", "definition": "Selecting a file permits local case finding, record checking and original inspection in this page. HaloPSA permits checking and inspection."},
    {"term": "Sharing", "definition": "No file upload, remote processing, evidence logging, application storage or sharing with another page."},
    {"term": "Retention", "definition": "Temporary while selected, including hidden tabs. Cancel keeps files for retry. Replacement, removal or a detected local date change requires reselection."},
    {"term": "Reset and exit", "definition": "Revoke access and remove selected files, results and retained originals. Restored pages require reselection. Pending native work cannot publish after removal."},
    {"term": "Saved copies", "definition": "Saving an original is your explicit action. Reset cannot delete your source, downloads, browser or operating-system copies and backups."},
    {"term": "Device access", "definition": "Processing uses this page and local workers. Your browser, device and extensions are outside this application permission boundary."}
  ];
  const glossary=async()=>{const o=await page.evaluate(async()=>{const d=(await import('/file-support.mjs')).glossaryProjection(),r=document.getElementById('file-support-contract'),t=document.getElementById('file-support-title');return{declared:d,frozen:Object.isFrozen(d)&&d.every(i=>Object.isFrozen(i)&&Object.keys(i).length===2&&typeof i.term==='string'&&typeof i.definition==='string'),title:t.textContent,titleTag:t.tagName,tag:r.tagName,direct:r.parentElement.id==='file-guide'&&t.parentElement===r.parentElement&&t.nextElementSibling===r,structure:r.childNodes.length===12&&[...r.childNodes].every(n=>n.nodeType===Node.ELEMENT_NODE&&n.tagName==='DIV'&&n.childNodes.length===2&&n.firstChild.tagName==='DT'&&n.lastChild.tagName==='DD'&&[n.firstChild,n.lastChild].every(v=>v.childNodes.length===1&&v.firstChild.nodeType===Node.TEXT_NODE)),rows:[...r.children].map(n=>({term:n.firstElementChild.textContent,definition:n.lastElementChild.textContent})),obsolete:document.querySelectorAll('#file-support-details,#file-support-summary,#file-guide p,#file-guide details').length};});need(o.frozen&&o.structure&&o.direct&&o.title==='File guide'&&o.titleTag==='H2'&&o.tag==='DL'&&!o.obsolete&&JSON.stringify(o.declared)===JSON.stringify(glossaryExpected)&&JSON.stringify(o.rows)===JSON.stringify(glossaryExpected)&&await page.locator('#file-support-contract dd:visible').count()===12,'Accessible glossary differs from twelve supported definitions: '+JSON.stringify(o));glossaries.push(o);};
  const truthful=async()=>{
    const rows=await page.locator('#record-info .claim-trail-row').evaluateAll(ns=>ns.map(n=>({field:n.dataset.field,original:n.querySelector(':scope > p').textContent,effective:n.querySelector('.claim-effective').textContent})));
    for(const key of ['reseller','distributor','billing','commitment','renewal','renewalDate']){const m=rows.filter(r=>r.field===key);need(m.length===1&&m[0].original==='No answer was collected for this field.'&&!/self.report|your answer|you answered|original questionnaire/i.test(m[0].effective),'Accessible omitted field invents a response: '+key+JSON.stringify(m));}
    need(rows.find(r=>r.field==='reseller').effective==='Value considered: Unknown. State: unknown. No answer was collected. An unestablished input cannot verify this fact.','Unknown reseller explanation claims response authority');omissions.push(rows);
    const copy=await page.locator('#record-info').textContent();need(!/your answer was|you answered|Questionnaire answers and the next-term selection are self-reported\./i.test(copy)&&copy.includes('No opening questionnaire answers were collected. Optional record-stage answers, when supplied, are self-reported.')&&copy.includes('Facts supplied by records')&&copy.includes('no opening answer was collected'),'Whole information copy implies phantom opening answers');
  };
  const pax='source_account_id,subscription_id,customer_ref,distributor,product_family,commerce_model,seat_based,commitment_term,renewal_date,end_of_term_state\naccount-a,sub-a11y,customer-a,pax8,Microsoft 365,NCE,yes,annual,2027-01-15,renew\n';
  const halo='line_id,subscription_id,customer_ref,billing_system\nline-a11y,sub-a11y,customer-a,HaloPSA\n';
  const file=async(id,text)=>page.locator('#'+id).setInputFiles({name:id+'.csv',mimeType:'text/csv',buffer:Buffer.from(text)});
  const discovered=async()=>{await page.locator('#case-choice').waitFor({state:'visible'});await page.waitForFunction(()=>document.querySelector('#case-choice option[value="1"]:not([disabled])')&&document.getElementById('cancel-case-finder').hidden);};
  const supply=async()=>{await file('halo-file',halo);await file('pax-file',pax);await discovered();need(await page.locator('#subscription-id').inputValue()==='','Discovery auto-selected a case');};
  const rerun=async()=>{await primary().click();await heading('Confirm these records describe the same case');await confirm().click();await heading('More evidence is needed');await truthful();await quiet();await noGreen();await safe();};

  await page.setViewportSize({width:1024,height:900});await boot();await quiet();await readableOpener('initial-direct-controls');
  need(await page.locator('#fit-form,#result,#next,#additional-facts,#load-case-finder,#change-case,input[type=radio]').count()===0&&await page.locator('#renewal-term').inputValue()==='not-asked'&&await page.locator('#agreement').inputValue()==='not-asked','Initial controls imply a questionnaire/response');
  await scan('direct-records-initial');
  await page.locator('#open-file-guide').focus();await page.keyboard.press('Enter');
  need(await page.locator('#file-guide').isVisible()&&await page.locator('#preflight').isHidden()&&await page.evaluate(()=>document.activeElement.id)==='close-file-guide','Keyboard glossary focus failed');await glossary();await scan('dedicated-file-guide');await page.keyboard.press('Enter');
  need(await page.locator('#file-guide').isHidden()&&await page.evaluate(()=>document.activeElement.id)==='open-file-guide','Glossary return lost focus');
  await evidence();await scan('empty-separate-evidence');await back();passed.push('DIRECT-A11Y-01-entry-guide');passed.push('DIRECT-A11Y-10-minimal-glossary');
  need(await page.locator('.fact-controls option').evaluateAll(ns=>ns.length===9&&ns.every(n=>n.textContent.endsWith('.')))&&await page.locator('.fact-controls select').evaluateAll(ns=>ns.length===2&&ns.every(n=>getComputedStyle(n).fontFamily==='system-ui, sans-serif'&&getComputedStyle(n).fontSize==='19px'&&n.getBoundingClientRect().height>=48)),'Native compact options lost full stops/19px typography/targets');
  await page.locator('#renewal-term').focus();await page.keyboard.press('ArrowDown');need(await page.locator('#renewal-term').inputValue()==='annual','Native term select ArrowDown failed');await page.keyboard.press('ArrowDown');need(await page.locator('#renewal-term').inputValue()==='monthly','Native term select second ArrowDown failed');await page.locator('#renewal-term').selectOption('annual');
  await page.locator('#agreement').focus();await page.keyboard.press('ArrowDown');need(await page.locator('#agreement').inputValue()==='yes','Native agreement select ArrowDown failed');await scan('compact-native-facts');
  await primary().click();await heading('Repair the supplied input');await quiet();
  need(await page.evaluate(()=>document.activeElement.textContent)==='Correct the supplied input','Missing-upload primary repair did not receive focus');await scan('missing-upload-repair-controls');
  await evidence();await scan('missing-upload-repair-information');await back();
  await page.getByRole('button',{name:'Correct the supplied input',exact:true}).focus();await page.keyboard.press('Enter');need(await page.evaluate(()=>document.activeElement.id)==='pax-file','Keyboard input repair missed picker');await safe();passed.push('DIRECT-A11Y-02-native-options-input-repair');
  await supply();await primary().click();await heading('Select one subscription');await quiet();await scan('missing-subscription-identity');
  await page.getByRole('button',{name:'Correct subscription ID',exact:true}).focus();await page.keyboard.press('Enter');need(await page.evaluate(()=>document.activeElement.id)==='subscription-id','Keyboard ID repair missed input');
  await file('pax-file',pax);await discovered();need(await page.locator('#subscription-id').inputValue()==='','Discovery automatically confirmed identity');
  await page.locator('#case-query').fill('unmatched-customer');await page.waitForFunction(()=>document.querySelector('#case-choice')?.options.length===1);await page.locator('#case-query').fill('');await discovered();await scan('native-automatic-case-finder');
  await page.locator('#case-choice').focus();await page.keyboard.press('ArrowDown');
  need(await page.locator('#subscription-id').inputValue()==='sub-a11y'&&await page.evaluate(()=>document.activeElement.textContent)==='Check records'&&await page.locator('#evidence-panels').isHidden(),'Native keyboard case choice lost ID/focus or opened information automatically');
  await evidence();await scan('selected-case-evidence');await back();passed.push('DIRECT-A11Y-03-explicit-case-selection');
  await page.locator('#renewal-term').selectOption('annual');await page.locator('#agreement').selectOption('yes');await primary().click();await heading('Confirm these records describe the same case');await quiet();
  need(await page.getByRole('button',{name:/Use supplied .* value/}).count()===0&&await page.locator('#record-info button').count()===0,'Unconfirmed sources exposed conflict controls');await noGreen();await scan('record-link-confirmation-controls');
  const linkWorkers=workers.length,linkCopy=await page.locator('#record-info').textContent();
  await page.evaluate(()=>{window.__savedConfirmation=document.querySelector('#record-result > button');window.__confirmationClicks=0;__savedConfirmation.addEventListener('click',()=>__confirmationClicks++);});await evidence();await scan('record-link-confirmation-information');
  const hiddenConfirmation=await page.evaluate(()=>{const connected=__savedConfirmation.isConnected;__savedConfirmation.click();return{connected,clicks:__confirmationClicks};});await page.waitForTimeout(100);
  need(hiddenConfirmation.connected&&hiddenConfirmation.clicks===1&&await page.locator('#record-info').textContent()===linkCopy&&workers.length===linkWorkers,'Saved hidden confirmation changed authority or admitted work');await safe();await noGreen();await back();passed.push('DIRECT-A11Y-11-hidden-confirmation-no-authority');
  await confirm().focus();await page.keyboard.press('Enter');await heading('More evidence is needed');await truthful();await quiet();await noGreen();
  need(await page.evaluate(()=>document.activeElement.textContent)==='Update the item to verify','Primary unresolved action did not receive focus');await scan('unresolved-reseller-controls');
  await page.keyboard.press('Enter');
  need(await page.locator('#evidence-panels').isVisible()&&await page.locator('#preflight').isHidden()&&await page.locator('#record-info .claim-trail').evaluate(n=>n.open)&&/Review the values considered/.test(await page.evaluate(()=>document.activeElement.textContent)),'Omitted-answer repair did not navigate to reference claim trail');
  await scan('expanded-unknown-source-review');await safe();passed.push('DIRECT-A11Y-04-link-before-unresolved-reseller');passed.push('DIRECT-A11Y-08-truthful-omitted-answers');
  await page.evaluate(()=>{window.__a11yFiles=[document.getElementById('pax-file').files[0],document.getElementById('halo-file').files[0]];window.__a11yInfo={text:document.getElementById('record-info').textContent,nodes:[...document.getElementById('record-info').childNodes]};});
  const original=page.locator('#original-pax-file');if(!await original.evaluate(n=>n.open)){await original.locator(':scope > summary').focus();await page.keyboard.press('Enter');}
  const pending=page.waitForEvent('download');await original.getByRole('button',{name:'Save original Pax8 copy',exact:true}).focus();await page.keyboard.press('Enter');
  const d=await pending,stream=await d.createReadStream(),parts=[];for await(const p of stream)parts.push(p);need(Buffer.concat(parts).equals(Buffer.from(pax)),'Keyboard original recovery changed exact bytes');
  await back();await readableOpener('finished-information-deferred');await quiet();await noGreen();await safe();
  need(await page.evaluate(()=>__a11yFiles[0]===document.getElementById('pax-file').files[0]&&__a11yFiles[1]===document.getElementById('halo-file').files[0]&&__a11yInfo.text===document.getElementById('record-info').textContent&&__a11yInfo.nodes.every((n,i)=>n===document.getElementById('record-info').childNodes[i]))&&await page.locator('.save-original').count()===2,'Information return lost finished ownership or original custody');await scan('retained-authority-controls');passed.push('DIRECT-A11Y-09-hidden-information-keyboard-custody');
  for(const width of [375,320]){
    await page.setViewportSize({width,height:740});await quiet();need(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Controls overflow mobile');await scan('record-controls-width'+width);
    await evidence();need(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Evidence overflows mobile');await scan('record-information-width'+width);await back();
    await page.locator('#open-file-guide').focus();await page.keyboard.press('Enter');await glossary();await scan('file-guide-width'+width);need(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Glossary overflows mobile');
    await page.locator('#close-file-guide').focus();await page.keyboard.press('Enter');need(await page.evaluate(()=>document.activeElement.id)==='open-file-guide'&&await page.locator('#record-info').textContent()===''&&await page.locator('#record-result').isHidden(),'Mobile glossary lost focus or revived old comparison');await rerun();
  }passed.push('DIRECT-A11Y-05-mobile375-320');
  await file('halo-file',halo.replace('customer-a','customer-b'));await discovered();await page.locator('#subscription-id').fill('sub-a11y');await primary().click();await heading('Confirm the record link');await quiet();
  need(await confirm().count()===0&&await page.getByRole('button',{name:/Use supplied .* value/}).count()===0,'Wrong customer link exposed attestation/source resolution');await noGreen();await scan('wrong-customer-record-link-controls');
  await evidence();await scan('wrong-customer-record-link-information');await back();await page.locator('#record-result > button').first().focus();await page.keyboard.press('Enter');need(['pax-file','halo-file'].includes(await page.evaluate(()=>document.activeElement.id)),'Link repair missed picker');await safe();passed.push('DIRECT-A11Y-06-wrong-link-blocks');
  await page.emulateMedia({forcedColors:'active'});await readableOpener('forced-colors-deferred-information');await scan('record-controls-forced-colors');
  await page.locator('#open-evidence').focus();const forced=await page.evaluate(()=>({active:document.activeElement.id,outlineStyle:getComputedStyle(document.activeElement).outlineStyle,outlineWidth:parseFloat(getComputedStyle(document.activeElement).outlineWidth)}));need(forced.active==='open-evidence'&&forced.outlineStyle!=='none'&&forced.outlineWidth>=2,'Forced-colors navigation focus indicator missing');await page.keyboard.press('Enter');await scan('record-information-forced-colors');await back();
  await page.locator('#open-file-guide').focus();await page.keyboard.press('Enter');await glossary();await scan('file-guide-forced-colors');await page.locator('#close-file-guide').click();await page.emulateMedia({forcedColors:'none'});await safe();passed.push('DIRECT-A11Y-07-forced-colors');
  await page.setViewportSize({width:1024,height:900});await boot();await supply();await page.locator('#case-choice').selectOption('1');await rerun();
  need(await page.locator('#renewal-term').inputValue()==='not-asked'&&await page.locator('#agreement').inputValue()==='not-asked','Uncollected optional fields were fabricated');
  const notAsked=await page.locator('#record-info').evaluate(r=>({term:r.querySelector('[data-record-projection=term]').textContent,rows:['renewalTerm','agreement'].map(f=>{const n=r.querySelector('.claim-trail-row[data-field="'+f+'"]');return{field:f,original:n.querySelector(':scope > p').textContent,effective:n.querySelector('.claim-effective').textContent};})}));
  need(notAsked.term==='No next commitment term answer was collected. The next term remains unestablished.'&&notAsked.rows.every(r=>r.original==='No answer was collected for this field.'&&r.effective==='Value considered: Not answered. State: not-asked. No answer was collected. This fact remains unestablished.'),'Uncollected next term/agreement gained response authority');await scan('uncollected-optional-controls');await evidence();const trail=page.locator('#record-info .claim-trail');if(!await trail.evaluate(n=>n.open))await trail.locator(':scope > summary').click();await scan('uncollected-optional-information');await back();await noGreen();await safe();passed.push('DIRECT-A11Y-12-uncollected-next-term-and-agreement');
  need(requests.every(r=>r.method==='GET'&&(new URL(r.url).origin===origin||r.url.startsWith('blob:'+origin+'/'))),'Remote accessibility dependency or data transmission');
  need(workers.length>0&&workers.every(u=>new URL(u).origin===origin&&new URL(u).pathname==='/file-processing-worker.mjs'),'Native local processing Workers bypassed');need(!errors.length&&!violations.length,JSON.stringify({errors,violations}));
  return'PASS: '+JSON.stringify({assertions:passed,scans,omissions,openerChecks,glossaries,hiddenConfirmation,notAsked,keyboardOriginalBytes:Buffer.byteLength(pax),checkerVersion:'4.10.3',superseded:'Native compact selects/automatic discovery/case choice and information-page navigation replace radio/Find-button/inline-disclosure checks.',scope:'Current local controls/information/glossary; automated WCAG A/AA, keyboard,320/375px and forced-colors only; no manual AT or universal accessibility acceptance.'});
}

